[package]
name = "uart-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
rand = "0.7"
btleplug = { version = "0.5.4", features = ["serde"] }
rumble = "0.3.0"